name: Health

# This would schedule it to run every day at 5:30 and 17:30 but commented it out so it won't keep running every day
# on:
#   schedule:
#     - cron:  '30 5,17 * * *'

on:
    push:
        branches:
            - master
    pull_request:
        branches: [master]
        types: [opened, synchronize]

jobs:
  check_health: 
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://pokedex-hjtw.onrender.com
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          details: health Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failuire
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          details: health Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
